spring:


  kafka:
      #      request.timeout.ms: 50000
    consumer:
      bootstrap-servers: 172.24.199.219:9092
      enable-auto-commit: false
      group-id: ${spring.application.name}
    listener:
      ack-mode: record


  redis:
    host: bitell-redis-rss-master
    port: 6379
    timeout: 2s
    database: 8

gateway:
  resubmitOpen: false