spring:
  redis:
    host: 192.168.0.201
    port: 6379
    timeout: 2s
    database: 8
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 1000s

  kafka:
      #      request.timeout.ms: 50000
    consumer:
      bootstrap-servers: 192.168.0.206:9092
      enable-auto-commit: false
      group-id: ${spring.application.name}
    listener:
      ack-mode: record




gateway:
  allowOrigins:
    - http://192.168.0.206:7001
    - http://192.168.0.131:7001
    - http://127.0.0.1:5500
    - http://192.168.0.145:5500
  resubmitOpen: true






